customizations:
  cloudFormationStacks:
    - deploymentTargets:
        accounts:
          - LogArchive
      description: Sample stack description
      name: Custom-LogGroup-Stack
      regions:
        - us-east-1
      runOrder: 1
      template: templates/loggroup.yaml
      terminationProtection: false
